### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by hyperfocus1337** [ObserverOfTime/jsonresume-theme-relaxed#7]
Bumping in the following issue after `npm install`

```
resume serve --theme ../json-resume-themes/jsonresume-theme-relaxed/

Preview: http://localhost:4000
Press ctrl-c to stop

RangeError: Invalid time value
    at Object.format (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/index.js:94:70)
    at eval (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:798:31)
    at out (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:70:13)
    at div (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:150:5)
    at eval (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:792:17)
    at out (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:70:13)
    at section (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:195:5)
    at fn$ (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:778:15)
    at eval (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:775:20)
    at out (eval at commonCompile (/Users/user/Repositories/resume/json-resume-themes/jsonresume-theme-relaxed/node_modules/@chronobserver/htmls/lib/index.js:68:10), <anonymous>:70:13)
Could not run the render function from local theme.
```

**Comment by ObserverOfTime** [comment]
The dates must be in `YYYY-MM` or `YYYY-MM-DD` format.
